import { Inter } from "next/font/google";
import "./globals.css";
import Header from '../components/Header'
import Navbar from '@/components/NavBar'
import Footer from '@/components/Footer'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
        <Navbar/>
        {children}</body>
    </html>
  );
}
